#!/usr/bin/env python3
"""Generate Reverie's CC0 starter music pack.

These are *original algorithmic compositions* synthesized from scratch —
additive pads, sine sub-bass, plucked bells, optional soft percussion, and a
Schroeder reverb. No sampled, recorded, or copyrighted material is involved,
so the output carries no third-party rights and is released into the public
domain under CC0-1.0. Chord progressions are generic harmonic building blocks
(not copyrightable); every waveform here is generated by this script.

Usage:
    python3 generate_music.py [outdir]     # default: ./music

Requires `lame` on PATH for MP3 encoding + ID3 tags.
"""
import array
import json
import math
import os
import subprocess
import sys

SR = 32000
LUT_N = 4096
SINE = [math.sin(2.0 * math.pi * i / LUT_N) for i in range(LUT_N)]
MASK = LUT_N - 1

ARTIST = "Reverie"
ALBUM = "Starter Worlds"
LICENSE = "CC0-1.0"


# ---------------------------------------------------------------------------
# Pitch helpers
# ---------------------------------------------------------------------------
_NOTE = {"C": 0, "D": 2, "E": 4, "F": 5, "G": 7, "A": 9, "B": 11}


def hz(name):
    """Note name like 'C3', 'F#4', 'Bb2' -> frequency in Hz (A4 = 440)."""
    letter = name[0].upper()
    i = 1
    semis = _NOTE[letter]
    if i < len(name) and name[i] in "#b":
        semis += 1 if name[i] == "#" else -1
        i += 1
    octave = int(name[i:])
    midi = semis + (octave + 1) * 12
    return 440.0 * (2.0 ** ((midi - 69) / 12.0))


# ---------------------------------------------------------------------------
# Envelopes (precomputed per event, indexed per sample)
# ---------------------------------------------------------------------------
def ramp_env(n, attack, release):
    """Raised-cosine attack/release window of length n samples."""
    a = max(1, int(attack * SR))
    r = max(1, int(release * SR))
    env = array.array("d", bytes(8 * n))
    for i in range(n):
        if i < a:
            g = 0.5 - 0.5 * math.cos(math.pi * i / a)
        elif i > n - r:
            k = (n - i) / r
            g = 0.5 - 0.5 * math.cos(math.pi * k)
        else:
            g = 1.0
        env[i] = g
    return env


def pluck_env(n, decay):
    """Exponential pluck: instant attack, exp decay over `decay` seconds."""
    env = array.array("d", bytes(8 * n))
    k = 1.0 / (decay * SR)
    for i in range(n):
        env[i] = math.exp(-k * i)
    return env


# ---------------------------------------------------------------------------
# Voices — each adds into stereo buffers L, R
# ---------------------------------------------------------------------------
def add_sine(L, R, start, freq, amp, env, panL, panR, detune=0.0):
    """Add a LUT sine of `freq` Hz into [start, start+len(env)) with `env`."""
    n = len(env)
    total = len(L)
    inc = LUT_N * freq * (2.0 ** (detune / 1200.0)) / SR
    ph = 0.0
    for i in range(n):
        j = start + i
        if j >= total:
            break
        s = SINE[int(ph) & MASK] * amp * env[i]
        L[j] += s * panL
        R[j] += s * panR
        ph += inc


def add_noise(L, R, start, env, amp, seed, panL, panR):
    """Add a short filtered-noise burst (a soft hat)."""
    n = len(env)
    total = len(L)
    x = seed & 0x7FFFFFFF
    prev = 0.0
    for i in range(n):
        j = start + i
        if j >= total:
            break
        x = (1103515245 * x + 12345) & 0x7FFFFFFF
        w = (x / 0x3FFFFFFF) - 1.0
        hp = w - prev  # 1-pole highpass → brighter, hat-like
        prev = w
        s = hp * amp * env[i]
        L[j] += s * panL
        R[j] += s * panR


def add_chord_pad(L, R, start, dur, freqs, amp):
    """A warm two-layer detuned pad holding `freqs` for `dur` seconds."""
    n = int(dur * SR)
    env = ramp_env(n, attack=0.9, release=1.1)
    for f in freqs:
        add_sine(L, R, start, f, amp, env, 0.62, 0.42, detune=-6.0)
        add_sine(L, R, start, f, amp, env, 0.42, 0.62, detune=+6.0)


def add_kick(L, R, start):
    """Sine kick with a fast pitch drop."""
    n = int(0.16 * SR)
    total = len(L)
    ph = 0.0
    for i in range(n):
        j = start + i
        if j >= total:
            break
        t = i / SR
        f = 42.0 + 78.0 * math.exp(-t * 34.0)
        e = math.exp(-t * 16.0)
        s = math.sin(ph) * 0.9 * e
        L[j] += s
        R[j] += s
        ph += 2.0 * math.pi * f / SR


# ---------------------------------------------------------------------------
# Composition
# ---------------------------------------------------------------------------
def render_track(spec):
    """Render one track spec to interleaved 16-bit stereo bytes."""
    bpm = spec["bpm"]
    beat = 60.0 / bpm
    chord_beats = spec.get("chord_beats", 8)
    chord_dur = beat * chord_beats
    prog = spec["prog"]
    loops = spec["loops"]

    total_secs = chord_dur * len(prog) * loops + 2.0
    total = int(total_secs * SR)
    L = array.array("d", bytes(8 * total))
    R = array.array("d", bytes(8 * total))

    rng = spec["seed"]

    def rand():
        nonlocal rng
        rng = (1103515245 * rng + 12345) & 0x7FFFFFFF
        return rng / 0x7FFFFFFF

    t = 0.0
    for _loop in range(loops):
        for chord in prog:
            start = int(t * SR)
            root = hz(chord["bass"])
            pad_freqs = [hz(nm) for nm in chord["pad"]]

            # Sub-bass on the chord root.
            add_sine(
                L, R, start, root, 0.34,
                ramp_env(int(chord_dur * SR), 0.05, 0.4),
                0.5, 0.5,
            )
            # Warm pad.
            add_chord_pad(L, R, start, chord_dur, pad_freqs, spec["pad_amp"])

            # Bell / arp figure on a beat grid.
            steps = int(chord_beats / spec["arp_every"])
            for s in range(steps):
                if rand() > spec["arp_density"]:
                    continue
                bt = t + s * spec["arp_every"] * beat
                bstart = int(bt * SR)
                note = pad_freqs[int(rand() * len(pad_freqs))] * 2.0
                env = pluck_env(int(0.7 * SR), 0.55)
                pan = 0.30 + 0.40 * rand()
                add_sine(L, R, bstart, note, 0.16, env, 1.0 - pan, pan)
                # Two soft echoes.
                for k, g in ((1, 0.5), (2, 0.28)):
                    est = int((bt + k * beat * 0.5) * SR)
                    add_sine(L, R, est, note, 0.16 * g, env, pan, 1.0 - pan)

            # Optional percussion.
            if spec.get("drums"):
                for b in range(chord_beats):
                    bstart = int((t + b * beat) * SR)
                    if b % 2 == 0:
                        add_kick(L, R, bstart)
                    else:
                        add_noise(
                            L, R, bstart, pluck_env(int(0.05 * SR), 0.03),
                            0.10, spec["seed"] + b, 0.5, 0.5,
                        )
            t += chord_dur

    reverb(L, R, wet=spec.get("reverb", 0.26))
    return finalize(L, R)


def reverb(L, R, wet):
    """A small Schroeder reverb (4 combs + 2 allpass) on the mono send."""
    n = len(L)
    mono = array.array("d", bytes(8 * n))
    for i in range(n):
        mono[i] = 0.5 * (L[i] + R[i])

    combs = [(1687, 0.78), (1913, 0.80), (2143, 0.82), (2371, 0.76)]
    acc = array.array("d", bytes(8 * n))
    for delay, fb in combs:
        buf = array.array("d", bytes(8 * n))
        for i in range(n):
            d = buf[i - delay] if i >= delay else 0.0
            buf[i] = mono[i] + d * fb
            acc[i] += buf[i] * 0.25

    for delay, g in ((347, 0.7), (113, 0.7)):
        out = array.array("d", bytes(8 * n))
        for i in range(n):
            d = out[i - delay] if i >= delay else 0.0
            out[i] = -g * acc[i] + d + g * (acc[i - delay] if i >= delay else 0.0)
        acc = out

    # Stereo spread: tiny inter-channel delay on the wet return.
    off = 240
    for i in range(n):
        L[i] += wet * acc[i]
        R[i] += wet * (acc[i - off] if i >= off else 0.0)


def finalize(L, R):
    """Soft-clip, peak-normalize, interleave to 16-bit LE bytes."""
    n = len(L)
    peak = 1e-9
    for i in range(n):
        L[i] = math.tanh(L[i] * 1.1)
        R[i] = math.tanh(R[i] * 1.1)
        peak = max(peak, abs(L[i]), abs(R[i]))
    g = 0.89 / peak
    out = array.array("h", bytes(2 * 2 * n))
    for i in range(n):
        out[2 * i] = int(max(-32768, min(32767, L[i] * g * 32767)))
        out[2 * i + 1] = int(max(-32768, min(32767, R[i] * g * 32767)))
    return out.tobytes()


def write_wav(path, pcm):
    import wave

    w = wave.open(path, "w")
    w.setnchannels(2)
    w.setsampwidth(2)
    w.setframerate(SR)
    w.writeframes(pcm)
    w.close()


# ---------------------------------------------------------------------------
# Track specs — varied key/tempo/energy so the analysis pipeline maps each to
# a different world. Progressions use generic diatonic chords.
# ---------------------------------------------------------------------------
TRACKS = [
    {
        "title": "Amber Drift",
        "bpm": 68, "seed": 101, "loops": 2, "chord_beats": 8,
        "arp_every": 1.0, "arp_density": 0.45, "pad_amp": 0.15, "reverb": 0.30,
        "drums": False,
        "prog": [
            {"bass": "C2", "pad": ["C4", "E4", "G4", "B4"]},
            {"bass": "F2", "pad": ["C4", "F4", "A4", "E5"]},
            {"bass": "A2", "pad": ["C4", "E4", "A4", "G5"]},
            {"bass": "G2", "pad": ["B3", "D4", "G4", "E5"]},
        ],
    },
    {
        "title": "Tidewater",
        "bpm": 60, "seed": 202, "loops": 2, "chord_beats": 8,
        "arp_every": 2.0, "arp_density": 0.4, "pad_amp": 0.15, "reverb": 0.34,
        "drums": False,
        "prog": [
            {"bass": "D2", "pad": ["D4", "F4", "A4", "E5"]},
            {"bass": "G2", "pad": ["D4", "G4", "B4", "F5"]},
            {"bass": "D2", "pad": ["D4", "F4", "A4", "C5"]},
            {"bass": "A#1", "pad": ["D4", "F4", "A4", "D5"]},
        ],
    },
    {
        "title": "Nightglass",
        "bpm": 92, "seed": 303, "loops": 3, "chord_beats": 8,
        "arp_every": 0.5, "arp_density": 0.5, "pad_amp": 0.13, "reverb": 0.24,
        "drums": True,
        "prog": [
            {"bass": "A1", "pad": ["A3", "C4", "E4", "G4"]},
            {"bass": "F1", "pad": ["A3", "C4", "F4", "A4"]},
            {"bass": "C2", "pad": ["C4", "E4", "G4", "B4"]},
            {"bass": "G1", "pad": ["B3", "D4", "G4", "D5"]},
        ],
    },
    {
        "title": "Emberfall",
        "bpm": 112, "seed": 404, "loops": 3, "chord_beats": 8,
        "arp_every": 0.5, "arp_density": 0.6, "pad_amp": 0.12, "reverb": 0.20,
        "drums": True,
        "prog": [
            {"bass": "E2", "pad": ["E4", "G4", "B4", "D5"]},
            {"bass": "C2", "pad": ["C4", "E4", "G4", "B4"]},
            {"bass": "G2", "pad": ["G3", "B3", "D4", "F#4"]},
            {"bass": "D2", "pad": ["D4", "F#4", "A4", "C5"]},
        ],
    },
]


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "music"
    )
    os.makedirs(outdir, exist_ok=True)
    if not _have("lame"):
        sys.exit("error: `lame` not found on PATH (needed for MP3 encoding)")

    manifest = {"version": 1, "license": LICENSE, "tracks": []}
    for spec in TRACKS:
        title = spec["title"]
        slug = title.lower().replace(" ", "-")
        wav = os.path.join(outdir, slug + ".wav")
        mp3 = os.path.join(outdir, slug + ".mp3")
        print(f"==> rendering {title} ({spec['bpm']} BPM)…", flush=True)
        write_wav(wav, render_track(spec))
        subprocess.run(
            ["lame", "-V", "4", "--quiet", "--add-id3v2",
             "--tt", title, "--ta", ARTIST, "--tl", ALBUM, wav, mp3],
            check=True,
        )
        os.remove(wav)
        size = os.path.getsize(mp3)
        print(f"    {slug}.mp3  {size // 1024} KB", flush=True)
        manifest["tracks"].append({
            "title": title, "artist": ARTIST, "album": ALBUM,
            "file": slug + ".mp3", "license": LICENSE, "bpm": spec["bpm"],
        })

    with open(os.path.join(outdir, "music.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"done: {len(TRACKS)} tracks + music.json in {outdir}")


def _have(binary):
    from shutil import which

    return which(binary) is not None


if __name__ == "__main__":
    main()
